workflows:
  my-workflow:
    name: my IOS workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      ios_signing:
        provisioning_profiles:
         - omars_profile
        certificates:
         - main_certificate
      groups:
        - ios_config
        - appstore_credentials
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: pub get
        script: flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build ipa for distribution
        script: flutter build ipa --release --export-options-plist /Users/builder/export_options.plist
      - name: send api to appstore
        script: xcrun altool --upload-app --type ios -f build/ios/ipa/*.ipa --apiKey 3LV8R98333 --apiIssuer 42778bb3-bb39-478e-9490-ab59550cd559
    artifacts:
    - build/ios/*.ipa
#     - ios/build/ios/ipa/*.ipa
#       - build/ios/iphoneos/*.app
#       flutter: 3.3.3
# |
#             set -ex
#             cd ios
#             xcode-project build-ipa \
#               --workspace Runner.xcworkspace \
#               --scheme Runner \
#               --config Flutter/Release.xcconfig
