workflows:
  hello-world:
    name: Hello world workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    scripts: flutter build ipa
#     environment:
#       groups:
#         - ios_config
