workflows:
  my-workflow:
    name: my IOS workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      ios_signing:
        provisioning_profiles:
         - omars_profile
        certificates:
         - main_certificate
      groups:
        - ios_config
        - appstore_credentials
    integrations:
      app_store_connect: oMIRebwfuVU9pXS7Mz5u2-JDI8A0rbI_120vzD-PJVs
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: pub get
        script: flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build ipa for distribution
        script: flutter build ipa --release --export-options-plist /Users/builder/export_options.plist
    artifacts:
    - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
#       - name: Install pods
#         script: |
#           find . -name "Podfile" -execdir pod install \;
