workflows:
  my-workflow:
    name: my IOS workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        -
    scripts:
      - name: Build ipa for distribution
        script: flutter build ipa
    artifacts:
      - build/ios/ipa/*.ipa
