workflows:
  my-workflow:
    name: my IOS workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - ios_config
        - appstore_credentials
    scripts:
      - name: pub get
        script: flutter pub get
      - name: pub upgrade
        script: flutter pub upgrade
#       - name: enter
#         script: cd ios
#       - name: init pod
#         script: pod init
#       - name: install pods
#         script: pod install
      - name: Build ipa for distribution
        script: flutter build ipa
    artifacts:
      - build/ios/ipa/*.ipa
