workflows:
  my-workflow:
    name: my IOS workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      ios_signing:
        provisioning_profiles:
         - omars_profile
        certificates:
         - main_certificate
      groups:
        - ios_config
        - appstore_credentials
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: pub get
        script: flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build ipa for distribution
        script: |
            set -ex
            cd ios
            xcodebuild \
              -workspace Runner.xcworkspace \
              -scheme Runner \
              -config Flutter/Release.xcconfig \
              -sdk iphoneos -archivePath /Users/builder/clone/ios/Flutter/Runner.xcarchive
      - name: do ipa
        script: |
            set -ex
            cd ios
            xcodebuild \
              -exportArchive -archivePath /Users/builder/clone/ios/Flutter/Runner.xcarchive \
              -exportOptionsPlist /Users/builder/export_options.plist \
              -exportPath Flutter/Runner.ipa
    artifacts:
#       - build/ios/iphoneos/*.app
      - ios/Flutter/*.ipa
