name: link_speak
description: A new Flutter project.
publish_to: "none"
version: 43.1.0+63
environment:
  sdk: ">=2.17.6"
  flutter: ^3.3.1
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.8
  firebase_messaging: ^14.1.4
  cloud_functions: ^4.0.6
  provider: ^6.0.2
  intl: ^0.17.0-nullsafety.2
  flutter_svg: ^1.1.3
  wechat_assets_picker: ^7.3.0
  wechat_camera_picker: ^3.2.0+1
  path: ^1.8.0
  path_provider: ^2.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_switch: ^0.3.0-nullsafety.0
  badges: ^2.0.0-nullsafety.1
  page_transition: ^2.0.1-nullsafety.0
  flutter_easyloading: ^3.0.0
  grouped_list: ^5.1.2
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.0
  flutter_native_splash: ^2.2.7
  form_field_validator: ^1.1.0
  mime: ^1.0.0
  video_compress: ^3.1.0
  flutter_image_compress: ^1.1.0
  visibility_detector: ^0.3.3
  qr_flutter: ^4.0.0
  profanity_filter: ^2.0.0
  dart_ipify: ^1.1.1
  rxdart: ^0.27.1
  o_color_picker: ^1.0.1
  auth_buttons: ^3.0.0
  google_sign_in: ^5.1.0
  flutter_facebook_auth: ^4.4.0+1
  flutter_app_badger: ^1.3.0
  skeletons: ^0.0.3
  flutter_nsfw: ^0.0.4
  flutter_video_info: ^1.2.0
  sign_in_with_apple: ^4.1.0
  google_maps_flutter: ^2.2.2
  location: ^4.3.0
  google_place: ^0.4.3
  geocoding: ^2.0.1
  flutter_inappwebview: ^5.3.2
  flutter_linkify: ^5.0.2
  measured_size: ^1.0.0
  validators: ^3.0.0
  flip_card: ^0.6.0
  parallax_rain: ^1.1.0
  flutter_bounce: ^1.1.0
  just_audio: ^0.9.20
  permission_handler: ^9.2.0
  record: ^4.3.1
  extended_image: ^6.0.1
  audio_video_progress_bar: ^0.10.0
  animated_button: ^0.2.0
  flutter_typeahead: ^4.0.0
  detectable_text_field: ^2.0.3
  cube_transition_plus: ^2.0.1
  google_mobile_ads: ^2.3.0
  circular_countdown_timer: ^0.2.1
  blur: ^3.1.0
  video_thumbnail: ^0.5.0
  screen_capture_event: ^1.0.0+1
  mobile_scanner: ^2.0.0
  flutter_web_frame: ^0.0.3
  file_picker: ^5.2.2
  # qr_code_scanner: ^0.4.0
  # pinch_zoom: ^0.1.0
  # photo_manager: ^2.1.0+2
  # intl_phone_number_input: ^0.7.0+2
  # social_share: ^2.1.1
  # stamp_image: ^0.0.2
  # font_awesome_flutter: ^9.2.0
dev_dependencies:
  flutter_launcher_icons: ^0.10.0
dependency_overrides:
  firebase_core_platform_interface: 4.5.2
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt
    - assets/nsfw.tflite
    - assets/images/splash.png
    - assets/images/noposts.svg
    - assets/images/endgame.svg
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
