name: link_speak
description: A new Flutter project.
publish_to: 'none'
version: 10.1.0+30
environment:
  sdk: ">=2.12.0-259.12.beta"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  cloud_firestore: ^2.2.1
  firebase_storage: ^8.1.1
  firebase_messaging: ^10.0.1
  cloud_functions: ^3.0.3
  provider: ^6.0.2
  intl: ^0.17.0-nullsafety.2
  flutter_svg: ^0.22.0
  wechat_assets_picker: ^6.3.1
  path: ^1.8.0
  path_provider: ^2.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_switch: ^0.3.0-nullsafety.0
  badges: ^2.0.0-nullsafety.1
  page_transition: ^2.0.1-nullsafety.0
  flutter_easyloading: ^3.0.0
  grouped_list: ^4.0.0
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.0
  flutter_native_splash: ^1.1.7+1
  form_field_validator: ^1.1.0
  pinch_zoom: ^0.1.0
  mime: ^1.0.0
  video_compress: ^3.0.0
  flutter_image_compress: ^1.0.0
  visibility_detector: ^0.2.2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0
  profanity_filter: ^2.0.0
  dart_ipify: ^1.1.1
  rxdart: ^0.27.1
  o_color_picker: ^1.0.1
  auth_buttons: ^1.0.1+4
  google_sign_in: ^5.1.0
  flutter_facebook_auth: ^3.5.1
  flutter_app_badger: ^1.3.0
  skeletons: ^0.0.3
  native_admob_flutter: ^1.5.0
  flutter_nsfw: ^0.0.4
  flutter_video_info: ^1.2.0
  sign_in_with_apple: ^3.3.0
  google_maps_flutter: ^2.1.1
  shake: ^2.0.0
  location: ^4.3.0
  google_place: ^0.4.3
  geocoding: ^2.0.1
  flutter_inappwebview: ^5.3.2
  flutter_linkify: ^5.0.2
  measured_size: ^1.0.0
  validators: ^3.0.0
  flip_card: ^0.6.0
  # intl_phone_number_input: ^0.7.0+2
  # social_share: ^2.1.1
  # stamp_image: ^0.0.2
  # font_awesome_flutter: ^9.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt
    - assets/nsfw.tflite
    - assets/images/splash.png
    - assets/images/noposts.svg
    - assets/images/powered_by_google.png
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
