// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for macos - '
            'you can reconfigure this by running the FlutterFire CLI again.');
      case TargetPlatform.windows:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for windows - '
            'you can reconfigure this by running the FlutterFire CLI again.');
      case TargetPlatform.linux:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
            'you can reconfigure this by running the FlutterFire CLI again.');
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDXnNHNEwi0EnMoqa6736wkj99FQadBzvg",
      authDomain: "linkspeak-9817c.firebaseapp.com",
      projectId: "linkspeak-9817c",
      storageBucket: "linkspeak-9817c.appspot.com",
      messagingSenderId: "761764606457",
      appId: "1:761764606457:web:3cbf94dcce6e70b41bcd28",
      measurementId: "G-61L6Z8DSTB");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyAgxEU8OzCBbtGE3ctl5DBLELtgOUqmhM4',
      appId: '1:761764606457:android:c2e60f0db64a1ad31bcd28',
      messagingSenderId: '761764606457',
      projectId: 'linkspeak-9817c',
      storageBucket: 'linkspeak-9817c.appspot.com');

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyBC0Waje9kAnLXpGRm5odsPWgXW_5t59sk',
      appId: '1:761764606457:ios:c57ee2766e3274001bcd28',
      messagingSenderId: '761764606457',
      projectId: 'linkspeak-9817c',
      storageBucket: 'linkspeak-9817c.appspot.com',
      androidClientId:
          '761764606457-9hia55er9ak6ci8gvbbdrqh1714o9m7l.apps.googleusercontent.com',
      iosClientId:
          '761764606457-7ntrqcmvcno15cqsg4eob6atjqbe8cr7.apps.googleusercontent.com',
      iosBundleId: 'com.linkspeak.techlr');
}
