/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData globe_no_map = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chats = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upvote = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brochure = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData curve_arrow = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_cross_outlined_symbol = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_anchor_1_ = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData night = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_1_ = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reverse = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightning = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_stopping = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clubs = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hidden = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotlight = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
